'use client'

import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { AnalyticsSnapshot } from '@/lib/analytics/server'

type CurrencySeries = AnalyticsSnapshot['ninjaTraderGross']['byCurrency'][number]

function money(value: number, currency: string) {
  try { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency, maximumFractionDigits: 2 }).format(value / 100) }
  catch { return `${(value / 100).toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${currency}` }
}

export function NinjaTraderGrossCharts({ series }: { series: CurrencySeries[] }) {
  if (!series.length) return <div className="rounded-lg border border-dashed border-white/10 p-5 text-xs text-zinc-500">Sem ciclos de posição fechados com lado, valor do ponto e horários suficientes neste período. O histórico de execuções exposto pelo NinjaTrader é limitado à sessão disponível.</div>
  return <div className="space-y-4">{series.map((item) => <div key={item.currency} className="rounded-xl border border-white/[0.06] bg-black/10 p-4">
    <div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-medium text-zinc-200">P&amp;L bruto NinjaTrader · {item.currency}</p><p className="mt-1 text-[10px] text-zinc-500">{item.sampleSize} ciclos fechados · taxas {item.feesCents === null ? 'não confirmadas em todos os fills' : 'recebidas'}</p></div><div className="text-right"><p className="text-sm font-semibold text-white">{money(item.grossPnlCents, item.currency)}</p><p className="mt-1 text-[10px] text-zinc-500">líquido {item.netPnlCents === null ? 'indisponível' : money(item.netPnlCents, item.currency)}</p></div></div>
    <div className="grid gap-4 xl:grid-cols-2"><div><p className="mb-2 text-[10px] text-zinc-500">Curva acumulada bruta</p><div className="h-[240px] min-w-0"><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{ width: 520, height: 240 }}><AreaChart data={item.curve}><defs><linearGradient id={`gross-${item.currency.replace(/[^A-Za-z0-9]/g, '')}`} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#b9f227" stopOpacity={0.22} /><stop offset="100%" stopColor="#b9f227" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.07)" vertical={false} /><XAxis dataKey="at" tick={{ fill: '#71717a', fontSize: 9 }} tickFormatter={(value) => new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Sao_Paulo', day: '2-digit', month: '2-digit' }).format(new Date(value))} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#71717a', fontSize: 9 }} tickFormatter={(value: number) => (value / 100).toLocaleString('pt-BR')} axisLine={false} tickLine={false} width={58} /><Tooltip labelFormatter={(value) => new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Sao_Paulo', dateStyle: 'short', timeStyle: 'short' }).format(new Date(String(value)))} formatter={(value) => [money(Number(value), item.currency), 'P&L bruto acumulado']} contentStyle={{ background: '#101214', border: '1px solid rgba(255,255,255,.12)', borderRadius: 10, color: '#f4f4f5', fontSize: 11 }} /><Area dataKey="grossPnlCents" type="monotone" stroke="#b9f227" strokeWidth={2} fill={`url(#gross-${item.currency.replace(/[^A-Za-z0-9]/g, '')})`} /></AreaChart></ResponsiveContainer></div></div>
    <div><p className="mb-2 text-[10px] text-zinc-500">P&amp;L bruto diário</p><div className="h-[240px] min-w-0"><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{ width: 520, height: 240 }}><BarChart data={item.daily}><CartesianGrid stroke="rgba(255,255,255,.07)" vertical={false} /><XAxis dataKey="day" tick={{ fill: '#71717a', fontSize: 9 }} tickFormatter={(value) => new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Sao_Paulo', day: '2-digit', month: '2-digit' }).format(new Date(`${value}T12:00:00`))} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#71717a', fontSize: 9 }} tickFormatter={(value: number) => (value / 100).toLocaleString('pt-BR')} axisLine={false} tickLine={false} width={58} /><Tooltip formatter={(value) => [money(Number(value), item.currency), 'P&L bruto do dia']} contentStyle={{ background: '#101214', border: '1px solid rgba(255,255,255,.12)', borderRadius: 10, color: '#f4f4f5', fontSize: 11 }} /><Bar dataKey="grossPnlCents" radius={[4, 4, 0, 0]}>{item.daily.map((point) => <Cell key={point.day} fill={point.grossPnlCents < 0 ? '#fb7185' : '#b9f227'} />)}</Bar></BarChart></ResponsiveContainer></div></div></div>
  </div>)}</div>
}
