'use client'

import { defaultProfile, type AccountProfileId, type RiskCategory, type SimulatorRules } from '@/lib/account-simulator/types'

const input = 'mt-1.5 h-11 w-full rounded-lg border border-white/10 bg-[#0b0d0f] px-3 text-[13px] text-zinc-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#b9f227]'
const check = 'accent-[#b9f227]'
const moneyNumber = (cents: number) => (cents / 100).toFixed(2)
const toCents = (value: string) => Number.isFinite(Number(value)) ? Math.round(Number(value) * 100) : 0
const riskLabels: Record<RiskCategory, string> = { DIRECT: 'Direta', ABSORPTION: 'Absorção', CONVENTIONAL: 'Convencional' }

export function SimulatorRulesEditor({ rules, onChange, dateOrder, onDateOrderChange, canUseTradeRules, excludedCategoryTrades }: {
  rules: SimulatorRules
  onChange: (rules: SimulatorRules) => void
  dateOrder: 'auto' | 'dmy' | 'mdy'
  onDateOrderChange: (value: 'auto' | 'dmy' | 'mdy') => void
  canUseTradeRules: boolean
  excludedCategoryTrades: number
}) {
  const setProfile = (key: keyof SimulatorRules['profile'], value: number) => onChange({ ...rules, profile: { ...rules.profile, [key]: value } })
  const setIncluded = (category: RiskCategory, included: boolean) => onChange({ ...rules, includedCategories: { ...rules.includedCategories, [category]: included } })
  const setRisk = (category: RiskCategory, field: 'enabled' | 'riskCents', value: boolean | number) => onChange({ ...rules, riskByCategory: { ...rules.riskByCategory, [category]: { ...rules.riskByCategory[category], [field]: value } } })
  const usdField = (label: string, value: number, update: (cents: number) => void) => <label className="text-xs font-medium text-zinc-400">{label}<span className="mt-1.5 flex h-11 items-center rounded-lg border border-white/10 bg-[#0b0d0f] px-3 text-[13px] text-zinc-400 transition-colors focus-within:border-[#b9f227]/40">US$<input aria-label={label} className="h-full min-w-0 flex-1 bg-transparent pl-2 text-zinc-100 outline-none tabular-nums" type="number" min="0" step="0.01" value={moneyNumber(value)} onChange={(event) => update(toCents(event.target.value))} /></span></label>
  return <section className="rounded-2xl border border-white/[0.09] bg-[linear-gradient(160deg,#151819,#101213)] p-5 shadow-[0_18px_50px_rgba(0,0,0,.18)] sm:p-6">
    <div className="border-b border-white/[0.07] pb-4"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#c7f36a]">Parâmetros</p><h2 className="mt-1 text-base font-semibold tracking-tight text-zinc-100">Configurações da simulação</h2><p className="mt-1.5 text-xs leading-5 text-zinc-400">Regras hipotéticas para esta análise. Nenhuma conta real é alterada e nenhuma ordem é enviada.</p></div>
    <div className="mt-5 grid grid-cols-1 gap-x-3 gap-y-4 lg:grid-cols-2">
      <label className="text-[11px] text-zinc-500">Conta simulada<select className={input} value={rules.profile.id} onChange={(event) => onChange({ ...rules, profile: defaultProfile(event.target.value as AccountProfileId) })}><option value="50K">50K</option><option value="150K">150K</option></select></label>
      <label className="text-[11px] text-zinc-500">Modo<select className={input} value={rules.mode} onChange={(event) => onChange({ ...rules, mode: event.target.value as SimulatorRules['mode'] })}><option value="evaluation">Avaliação</option><option value="payout">Conta PA / saque</option></select></label>
      <label className="text-[11px] text-zinc-500">Regra de drawdown<select className={input} value={rules.drawdownRule} onChange={(event) => onChange({ ...rules, drawdownRule: event.target.value as SimulatorRules['drawdownRule'] })}><option value="closed-trade">Dinâmico por trade fechado</option><option value="end-of-day">Atualizar no fim do dia</option></select></label>
      <label className="text-[11px] text-zinc-500">Datas ambíguas no CSV<select className={input} value={dateOrder} onChange={(event) => onDateOrderChange(event.target.value as 'auto' | 'dmy' | 'mdy')}><option value="auto">Automática · Brasil se ambígua</option><option value="dmy">Dia / mês / ano</option><option value="mdy">Mês / dia / ano</option></select></label>
      {usdField('Saldo inicial', rules.profile.startBalanceCents, (value) => setProfile('startBalanceCents', value))}
      {usdField(rules.mode === 'evaluation' ? 'Meta para aprovação' : 'Meta de lucro para simular', rules.profile.targetCents, (value) => setProfile('targetCents', value))}
      {usdField('Limite de perda / DD inicial', rules.profile.maxLossCents, (value) => setProfile('maxLossCents', value))}
      {usdField('Descolar DD na conta PA', rules.profile.payoutDetachCents, (value) => setProfile('payoutDetachCents', value))}
      <label className="text-[11px] text-zinc-500">Fuso da conta<select className={input} value={rules.timezone} onChange={(event) => onChange({ ...rules, timezone: event.target.value })}><option value="America/New_York">Nova York · ET</option><option value="America/Chicago">Chicago · CT</option><option value="America/Sao_Paulo">São Paulo</option><option value="UTC">UTC</option></select></label>
      {usdField('Risco original de referência', rules.referenceRiskCents, (value) => onChange({ ...rules, referenceRiskCents: value }))}
    </div>
    {rules.profile.id === '150K' && (!rules.profile.targetCents || !rules.profile.maxLossCents) && <p className="mt-3 rounded-lg border border-amber-300/20 bg-amber-300/[0.04] p-3 text-[11px] leading-5 text-amber-100">Informe a meta e o limite de perda da sua regra 150K. A referência não confirma valores universais para essa conta.</p>}
    <div className="mt-5 grid grid-cols-1 gap-3 lg:grid-cols-2">
      <section className="rounded-xl border border-white/[0.07] bg-black/15 p-4 lg:col-span-2">
        <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xs font-semibold text-zinc-100">Tipos incluídos na simulação</h3><p className="mt-1 text-xs leading-5 text-zinc-400">Desmarque um tipo para removê-lo das curvas e métricas. Trades sem tipo identificado permanecem incluídos.</p></div>{excludedCategoryTrades > 0 && <span className="rounded-full border border-amber-300/15 bg-amber-300/[0.04] px-2.5 py-1 text-[10px] text-amber-100">{excludedCategoryTrades} operação(ões) removida(s)</span>}</div>
        <div className="mt-3 grid gap-2 sm:grid-cols-3">{(Object.keys(riskLabels) as RiskCategory[]).map((category) => <label key={category} className={`flex min-h-11 cursor-pointer items-center gap-2.5 rounded-lg border px-3 text-xs transition-colors ${rules.includedCategories[category] ? 'border-[#b9f227]/20 bg-[#b9f227]/[0.035] text-zinc-200' : 'border-white/[0.06] bg-black/10 text-zinc-500'}`}><input type="checkbox" className={check} checked={rules.includedCategories[category]} disabled={!canUseTradeRules} onChange={(event) => setIncluded(category, event.target.checked)} />{riskLabels[category]}</label>)}</div>
      </section>
      <section className="rounded-lg border border-white/[0.06] bg-black/10 p-3"><h3 className="text-xs font-semibold text-zinc-300">Risco por entrada</h3><p className="mt-1 text-[11px] leading-4 text-zinc-400">O resultado é reescalado pelo risco original do CSV ou pelo risco de referência.</p><div className="mt-3 grid grid-cols-1 gap-2">{(Object.keys(riskLabels) as RiskCategory[]).map((category) => <div key={category} className="flex items-center gap-2 rounded-lg border border-white/[0.05] p-2"><label className="flex min-w-0 flex-1 items-center gap-2 text-[11px] text-zinc-300"><input type="checkbox" className={check} checked={rules.riskByCategory[category].enabled} disabled={!canUseTradeRules} onChange={(event) => setRisk(category, 'enabled', event.target.checked)} />{riskLabels[category]}</label><label className="flex w-28 shrink-0 items-center gap-1 text-[11px] text-zinc-400">US$<input aria-label={`Risco ${riskLabels[category]}`} className="min-w-0 flex-1 rounded bg-[#0b0d0f] px-2 py-1.5 text-zinc-300" type="number" min="0" step="0.01" value={moneyNumber(rules.riskByCategory[category].riskCents)} disabled={!rules.riskByCategory[category].enabled || !canUseTradeRules} onChange={(event) => setRisk(category, 'riskCents', toCents(event.target.value))} /></label></div>)}</div></section>
      <section className="rounded-lg border border-white/[0.06] bg-black/10 p-3"><h3 className="text-xs font-semibold text-zinc-300">Entry Market</h3><label className="mt-2 flex items-center gap-2 text-[11px] text-zinc-400"><input type="checkbox" className={check} checked={rules.entryMarket.enabled} disabled={!canUseTradeRules} onChange={(event) => onChange({ ...rules, entryMarket: { ...rules.entryMarket, enabled: event.target.checked } })} />Aplicar filtro</label><div className="mt-2 flex gap-4 text-[11px] text-zinc-500"><label className="flex items-center gap-2"><input type="checkbox" className={check} checked={rules.entryMarket.allowBuy} disabled={!rules.entryMarket.enabled || !canUseTradeRules} onChange={(event) => onChange({ ...rules, entryMarket: { ...rules.entryMarket, allowBuy: event.target.checked } })} />Compra</label><label className="flex items-center gap-2"><input type="checkbox" className={check} checked={rules.entryMarket.allowSell} disabled={!rules.entryMarket.enabled || !canUseTradeRules} onChange={(event) => onChange({ ...rules, entryMarket: { ...rules.entryMarket, allowSell: event.target.checked } })} />Venda</label></div><p className="mt-2 text-[11px] leading-4 text-zinc-400">Trades sem rótulo Entry Market permanecem na curva; o filtro exige direção mapeada.</p></section>
      <section className="rounded-lg border border-white/[0.06] bg-black/10 p-3"><h3 className="text-xs font-semibold text-zinc-300">Trava diária</h3><label className="mt-2 flex items-center gap-2 text-[11px] text-zinc-400"><input type="checkbox" className={check} checked={rules.dailyLoss.enabled} disabled={!canUseTradeRules} onChange={(event) => onChange({ ...rules, dailyLoss: { ...rules.dailyLoss, enabled: event.target.checked } })} />Limitar perda líquida do dia</label>{usdField('Perda máxima diária', rules.dailyLoss.maxLossCents, (value) => onChange({ ...rules, dailyLoss: { ...rules.dailyLoss, maxLossCents: value } }))}<label className="mt-3 flex items-center gap-2 text-[11px] text-zinc-400"><input type="checkbox" className={check} checked={rules.dailyStops.enabled} disabled={!canUseTradeRules} onChange={(event) => onChange({ ...rules, dailyStops: { ...rules.dailyStops, enabled: event.target.checked } })} />Limitar número de stops</label><label className="mt-2 block text-[11px] text-zinc-500">Stops por dia<input className={input} type="number" min="1" step="1" disabled={!rules.dailyStops.enabled || !canUseTradeRules} value={rules.dailyStops.maxStops} onChange={(event) => onChange({ ...rules, dailyStops: { ...rules.dailyStops, maxStops: Math.max(1, Number(event.target.value) || 1) } })} /></label><label className="mt-2 flex items-center gap-2 text-[11px] text-zinc-500"><input type="checkbox" className={check} checked={rules.dailyStops.lossWithoutExitReasonIsStop} disabled={!rules.dailyStops.enabled || !canUseTradeRules} onChange={(event) => onChange({ ...rules, dailyStops: { ...rules.dailyStops, lossWithoutExitReasonIsStop: event.target.checked } })} />Contar toda perda como stop quando faltar motivo de saída</label><p className="mt-2 text-[11px] leading-4 text-zinc-400">A trava bloqueia trades seguintes do dia; o trade que atinge o limite permanece.</p></section>
      <section className="rounded-lg border border-white/[0.06] bg-black/10 p-3"><h3 className="text-xs font-semibold text-zinc-300">Tomahawk</h3><label className="mt-2 flex items-center gap-2 text-[11px] text-zinc-400"><input type="checkbox" className={check} checked={rules.tomahawk.enabled} disabled={!canUseTradeRules} onChange={(event) => onChange({ ...rules, tomahawk: { ...rules.tomahawk, enabled: event.target.checked } })} />Aumentar o risco com lucro do dia</label><label className="mt-3 block text-[11px] text-zinc-500">Percentual do lucro diário aplicado como risco adicional<input className={input} type="number" min="0" max="500" step="1" disabled={!rules.tomahawk.enabled || !canUseTradeRules} value={rules.tomahawk.profitPercent} onChange={(event) => onChange({ ...rules, tomahawk: { ...rules.tomahawk, profitPercent: Math.min(500, Math.max(0, Number(event.target.value) || 0)) } })} /></label><label className="mt-2 block text-[11px] text-zinc-500">Teto sobre o risco-base (×)<input className={input} type="number" min="1" max="10" step="0.1" disabled={!rules.tomahawk.enabled || !canUseTradeRules} value={rules.tomahawk.maxBaseMultiple} onChange={(event) => onChange({ ...rules, tomahawk: { ...rules.tomahawk, maxBaseMultiple: Math.min(10, Math.max(1, Number(event.target.value) || 1)) } })} /></label><p className="mt-2 text-[11px] leading-4 text-zinc-400">O risco recalcula após cada trade. Ao zerar ou ficar negativo no dia, volta ao risco-base.</p></section>
    </div>
    {!canUseTradeRules && <p className="mt-3 text-[11px] text-amber-200">Regras por operação ficam desativadas sem trades individuais reconhecidos.</p>}
  </section>
}
