'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, CircleDollarSign, Gauge, Plus, Wallet } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { FirmLogo } from '@/components/modules/accounts/firm-logo'
import { useDemoWorkspace } from '@/hooks/use-demo-workspace'
import { accountBalance, accountDailyLossUsePercent, calculatePerformance, dateRangeForPeriod, groupDailyPnl, selectAccounts, selectTrades, strategyNetPnl } from '@/lib/demo/selectors'
import { formatCurrency, formatDateTime, formatPercent } from '@/lib/format'
import { MetricTile, PageFrame, Panel, PrimaryButton, SectionHeading, StatusPill } from '@/components/workspace/primitives'

type Period = '7D' | '30D' | '90D' | 'YTD'

export function DashboardScreen() {
  const { workspace } = useDemoWorkspace()
  const [period, setPeriod] = useState<Period>('30D')
  const range = useMemo(() => dateRangeForPeriod(period, workspace.asOfDate), [period, workspace.asOfDate])
  const periodTrades = useMemo(() => selectTrades(workspace, range), [workspace, range])
  const summary = useMemo(() => calculatePerformance(periodTrades), [periodTrades])
  const activeAccounts = selectAccounts(workspace, { lifecycle: 'active' })
  const needsAttention = activeAccounts.filter((account) => account.drawdownBufferPercent < 40)
  const unreadAlerts = workspace.alertEvents.filter((event) => !event.readAt)
  const todayTrades = selectTrades(workspace, { from: `${workspace.asOfDate}T00:00:00-03:00`, to: `${workspace.asOfDate}T23:59:59.999-03:00` })
  const todayPnl = todayTrades.reduce((total, trade) => total + trade.netPnl, 0)
  const dailySeries = groupDailyPnl(periodTrades)
  let cumulative = 0
  const equitySeries = dailySeries.map((point) => { cumulative += point.pnl; return { ...point, equity: cumulative } })
  const strategies = [...workspace.strategies].map((strategy) => ({ ...strategy, pnl: strategyNetPnl(workspace, strategy.id, range.from, range.to) })).sort((a, b) => b.pnl - a.pnl)
  const avgBuffer = activeAccounts.length ? activeAccounts.reduce((sum, account) => sum + account.drawdownBufferPercent, 0) / activeAccounts.length : null
  const connectionCount = workspace.integrations.filter((item) => item.connectionState === 'connected').length
  const periods: Period[] = ['7D', '30D', '90D', 'YTD']

  return <PageFrame title="Visão geral da operação" description="Resumo do período com alertas e atalhos para os detalhes." eyebrow="OPERAÇÃO DEMONSTRATIVA" actions={<Link href="/accounts?new=1" className="primary-button min-h-9"><Plus className="size-4" /> Adicionar conta</Link>}>
    <section className="mb-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <MetricTile label={`P&L · ${period}`} value={formatCurrency(summary.netPnl)} icon={CircleDollarSign} tone={summary.netPnl < 0 ? 'negative' : 'positive'} note={`${summary.tradeCount} trades demonstrativos`} />
      <MetricTile label="P&L de hoje" value={formatCurrency(todayPnl)} icon={Activity} tone={todayPnl < 0 ? 'negative' : 'positive'} note={`${todayTrades.length} execuções na amostra`} />
      <MetricTile label="Buffer médio" value={avgBuffer == null ? '—' : formatPercent(avgBuffer / 100)} icon={Gauge} tone={needsAttention.length ? 'warning' : 'neutral'} note={`${needsAttention.length} ${needsAttention.length === 1 ? 'conta' : 'contas'} abaixo de 40%`} />
      <MetricTile label="Contas ativas" value={String(activeAccounts.length)} icon={Wallet} note={`${connectionCount} conexões reais · não configuradas nesta etapa`} />
    </section>

    <section className="mb-7 grid gap-4 xl:grid-cols-[1.45fr_1fr]">
      <Panel className="p-5 sm:p-6">
        <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><SectionHeading title="Curva de P&L" description={`Resultado agregado · ${summary.tradeCount} trades no período`} /><div className="flex items-center gap-1 rounded-lg bg-white/[0.035] p-1" aria-label="Selecionar período">{periods.map((option) => <button key={option} onClick={() => setPeriod(option)} aria-pressed={period === option} className={`rounded-md px-2.5 py-1.5 text-[10px] font-medium transition-colors ${period === option ? 'bg-white/[0.1] text-white' : 'text-zinc-500 hover:text-zinc-200'}`}>{option}</button>)}</div></div>
        <div className="mb-4 flex items-end gap-3"><span className={`text-2xl font-semibold tracking-tight ${summary.netPnl < 0 ? 'text-rose-300' : 'text-white'}`}>{formatCurrency(summary.netPnl)}</span><span className="mb-1 text-[10px] text-zinc-500">no intervalo escolhido</span></div>
        {equitySeries.length ? <div className="h-[260px] min-w-0" role="img" aria-label="Gráfico acumulado de P&L por dia"><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{ width: 600, height: 260 }}><AreaChart data={equitySeries} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}><defs><linearGradient id="dashboard-pnl" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#b9f227" stopOpacity={0.25} /><stop offset="95%" stopColor="#b9f227" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.07)" vertical={false} /><XAxis dataKey="label" tick={{ fill: '#71717a', fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#71717a', fontSize: 10 }} axisLine={false} tickLine={false} tickFormatter={(value: number) => `$${Math.round(value / 1000)}k`} width={48} /><Tooltip formatter={(value) => [formatCurrency(Number(value)), 'P&L acumulado']} contentStyle={{ background: '#101214', border: '1px solid rgba(255,255,255,.12)', borderRadius: 10, color: '#f4f4f5', fontSize: 12 }} labelStyle={{ color: '#a1a1aa' }} /><Area type="monotone" dataKey="equity" stroke="#b9f227" strokeWidth={2.5} fill="url(#dashboard-pnl)" /></AreaChart></ResponsiveContainer></div> : <div className="flex h-[260px] items-center justify-center rounded-lg border border-dashed border-white/10 text-xs text-zinc-500">Sem trades neste período demonstrativo.</div>}
      </Panel>

      <Panel className="p-5 sm:p-6">
        <SectionHeading title="Monitor de risco" description="Buffers sintéticos; regras apenas informativas." action={<Link href="/risk-command" className="text-[10px] font-medium text-[#b9f227] hover:underline">Abrir risco</Link>} />
        <div className="mb-5 grid grid-cols-2 gap-3"><div className="stat-tile"><p className="metric-label">Menor buffer</p><p className="mt-2 text-xl font-semibold text-amber-200">{needsAttention.length ? `${Math.min(...needsAttention.map((account) => account.drawdownBufferPercent))}%` : '—'}</p><p className="mt-2 text-[10px] text-zinc-500">{needsAttention[0]?.name ?? 'Nenhuma conta em atenção'}</p></div><div className="stat-tile"><p className="metric-label">Uso limite diário</p><p className="mt-2 text-xl font-semibold text-white">{formatPercent(activeAccounts.length ? activeAccounts.reduce((sum, account) => sum + accountDailyLossUsePercent(workspace, account), 0) / activeAccounts.length / 100 : null)}</p><p className="mt-2 text-[10px] text-zinc-500">média da amostra</p></div></div>
        {needsAttention.length ? <div className="flex items-start gap-3 rounded-lg border border-amber-300/15 bg-amber-300/[0.04] p-3"><AlertTriangle className="mt-0.5 size-4 shrink-0 text-amber-300" /><div><p className="text-xs font-medium text-amber-100">{needsAttention.length} {needsAttention.length === 1 ? 'conta com' : 'contas com'} buffer baixo</p><p className="mt-1 text-[11px] leading-relaxed text-zinc-500">{needsAttention.map((account) => `${account.name}: ${account.drawdownBufferPercent}%`).join(' · ')}. Somente dados de demonstração; nenhuma proteção está ativa.</p></div></div> : <div className="rounded-lg border border-emerald-400/10 bg-emerald-400/[0.03] p-3 text-xs text-zinc-400">Nenhuma conta de demonstração abaixo do limite de atenção.</div>}
        <div className="mt-5 border-t border-white/[0.06] pt-4"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-medium text-zinc-300">Alertas pendentes</span><Link href="/alerts" className="text-[10px] text-[#b9f227] hover:underline">Ver todos</Link></div>{unreadAlerts.length ? unreadAlerts.slice(0, 2).map((alert) => <p key={alert.id} className="mt-2 text-[11px] text-amber-100">{alert.message}</p>) : <p className="mt-2 text-[11px] text-zinc-500">Nenhum alerta pendente na amostra.</p>}</div>
      </Panel>
    </section>

    <section className="mb-7"><div className="mb-4 flex items-end justify-between gap-4"><div><SectionHeading title="Contas monitoradas" description="Resumo calculado a partir dos trades de demonstração." /></div><Link href="/accounts" className="mb-4 text-xs font-medium text-[#b9f227] hover:underline">Gerenciar contas</Link></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{activeAccounts.map((account) => { const pnl = accountBalance(workspace, account) - account.startingCapital; return <Link key={account.id} href={`/accounts#${account.id}`} className="account-card block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#b9f227]"><div className="mb-4 flex items-start justify-between gap-2"><div className="flex items-center gap-2"><FirmLogo firm={account.firm} customLogoUrl={account.firmLogoUrl} size={32} /><div><p className="text-sm font-semibold text-white">{account.name}</p><p className="mt-1 text-[9px] tracking-[0.16em] text-zinc-500">{account.firm} · {account.stage}</p></div></div><StatusPill tone={account.drawdownBufferPercent < 40 ? 'warning' : 'positive'}>{account.drawdownBufferPercent < 40 ? 'ATENÇÃO' : 'AMOSTRA'}</StatusPill></div><div className="grid grid-cols-2 gap-y-3"><div><p className="metric-label">Saldo</p><p className="mt-1 text-sm font-semibold text-white">{formatCurrency(accountBalance(workspace, account))}</p></div><div><p className="metric-label">P&amp;L da amostra</p><p className={`mt-1 text-sm font-semibold ${pnl < 0 ? 'text-rose-300' : 'text-[#b9f227]'}`}>{formatCurrency(pnl)}</p></div><div className="col-span-2"><div className="mb-1 flex justify-between text-[10px] text-zinc-500"><span>Buffer demonstrativo</span><span>{account.drawdownBufferPercent}%</span></div><div className="h-1 overflow-hidden rounded-full bg-white/[0.07]"><div className={`h-full rounded-full ${account.drawdownBufferPercent < 40 ? 'bg-amber-300' : 'bg-[#b9f227]'}`} style={{ width: `${account.drawdownBufferPercent}%` }} /></div></div></div></Link> })}</div></section>

    <section className="grid gap-4 xl:grid-cols-[1.6fr_1fr]">
      <Panel className="overflow-hidden"><div className="p-5 sm:p-6"><SectionHeading title="Trades recentes" description="Execuções sintéticas associadas às contas." /></div>{periodTrades.length ? <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-y border-white/[0.06] text-[9px] uppercase tracking-[0.14em] text-zinc-600"><th className="px-5 py-3">Horário</th><th className="px-3 py-3">Conta</th><th className="px-3 py-3">Estratégia</th><th className="hidden px-3 py-3 sm:table-cell">Instrumento</th><th className="px-5 py-3 text-right">P&amp;L</th></tr></thead><tbody>{periodTrades.slice(0, 6).map((trade) => <tr key={trade.id} className="border-b border-white/[0.04] last:border-0"><td className="whitespace-nowrap px-5 py-3 text-[10px] text-zinc-500">{formatDateTime(trade.closedAt)}</td><td className="whitespace-nowrap px-3 py-3 text-xs text-zinc-300">{workspace.accounts.find((account) => account.id === trade.accountId)?.name}</td><td className="whitespace-nowrap px-3 py-3 text-xs text-zinc-400">{workspace.strategies.find((strategy) => strategy.id === trade.strategyId)?.name ?? 'Sem estratégia'}</td><td className="hidden whitespace-nowrap px-3 py-3 font-mono text-[10px] text-zinc-500 sm:table-cell">{trade.instrument}</td><td className={`whitespace-nowrap px-5 py-3 text-right font-mono text-xs ${trade.netPnl < 0 ? 'text-rose-300' : 'text-[#b9f227]'}`}>{formatCurrency(trade.netPnl)}</td></tr>)}</tbody></table></div> : <p className="px-5 pb-5 text-xs text-zinc-500">Nenhum trade nesse período.</p>}</Panel>
      <Panel className="p-5 sm:p-6"><SectionHeading title="Resultado por estratégia" description="Contribuição no intervalo selecionado." /><div className="flex flex-col gap-4">{strategies.map((strategy) => <div key={strategy.id}><div className="mb-1.5 flex items-center justify-between gap-2"><span className="text-xs font-medium text-zinc-300">{strategy.name}</span><span className={`font-mono text-xs ${strategy.pnl < 0 ? 'text-rose-300' : 'text-[#b9f227]'}`}>{formatCurrency(strategy.pnl)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/[0.06]"><div className={`h-full rounded-full ${strategy.pnl < 0 ? 'bg-rose-300' : 'bg-[#b9f227]'}`} style={{ width: `${summary.netPnl > 0 ? Math.min(100, Math.abs(strategy.pnl / summary.netPnl) * 100) : 0}%` }} /></div><p className="mt-1.5 text-[10px] text-zinc-600">{strategy.status === 'configuration-pending' ? 'Regras pendentes · valores apenas demonstrativos' : strategy.status}</p></div>)}</div><div className="mt-5 rounded-lg border border-white/[0.06] bg-white/[0.02] p-3"><p className="text-[11px] text-zinc-300">Taxa de trades positivos</p><p className="mt-1 flex items-center gap-1 text-sm font-semibold text-[#b9f227]">{formatPercent(summary.winRate)} {summary.winRate == null ? null : summary.winRate >= 0.5 ? <ArrowUpRight className="size-3.5" /> : <ArrowDownRight className="size-3.5" />}</p></div></Panel>
    </section>
  </PageFrame>
}
