'use client'

import { useMemo, useState } from 'react'
import { Activity, CircleDollarSign, Target, TrendingDown } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { EmptyState, MetricTile, PageFrame, Panel, SectionHeading } from '@/components/workspace/primitives'
import { useDemoWorkspace } from '@/hooks/use-demo-workspace'
import { calculatePerformance, dateRangeForPeriod, groupDailyPnl, selectTrades } from '@/lib/demo/selectors'
import { formatCurrency, formatPercent, formatDateTime } from '@/lib/format'

type Period = '7D' | '30D' | '90D' | 'YTD'

export function PerformanceScreen() {
  const { workspace } = useDemoWorkspace()
  const [period, setPeriod] = useState<Period>('30D')
  const [accountId, setAccountId] = useState('all')
  const [strategyId, setStrategyId] = useState('all')
  const range = dateRangeForPeriod(period, workspace.asOfDate)
  const trades = useMemo(() => selectTrades(workspace, { from: range.from, to: range.to, accountId: accountId === 'all' ? undefined : accountId, strategyId: strategyId === 'all' ? undefined : strategyId }), [workspace, range.from, range.to, accountId, strategyId])
  const summary = calculatePerformance(trades)
  const daily = groupDailyPnl(trades)
  let running = 0
  const curve = daily.map((point) => { running += point.pnl; return { ...point, cumulative: running } })
  const selectClass = 'h-10 rounded-lg border border-white/10 bg-[#0b0d0f] px-3 text-xs text-zinc-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#b9f227]'

  return <PageFrame title="Desempenho" description="Resultados históricos com métricas calculadas sobre os trades filtrados." eyebrow="ANÁLISE DE RESULTADOS">
    <div className="mb-5 grid gap-2 sm:grid-cols-3"><label className="text-[10px] text-zinc-500">Período<select className={`${selectClass} mt-1 w-full`} value={period} onChange={(event) => setPeriod(event.target.value as Period)}><option value="7D">7 dias</option><option value="30D">30 dias</option><option value="90D">90 dias</option><option value="YTD">Ano até hoje</option></select></label><label className="text-[10px] text-zinc-500">Conta<select className={`${selectClass} mt-1 w-full`} value={accountId} onChange={(event) => setAccountId(event.target.value)}><option value="all">Todas as contas</option>{workspace.accounts.map((account) => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label className="text-[10px] text-zinc-500">Estratégia<select className={`${selectClass} mt-1 w-full`} value={strategyId} onChange={(event) => setStrategyId(event.target.value)}><option value="all">Todas as estratégias</option>{workspace.strategies.map((strategy) => <option value={strategy.id} key={strategy.id}>{strategy.name}</option>)}</select></label></div>
    <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="P&L líquido" value={formatCurrency(summary.netPnl)} icon={CircleDollarSign} tone={summary.netPnl < 0 ? 'negative' : 'positive'} note="Soma do P&L líquido dos trades selecionados." /><MetricTile label="Taxa positiva" value={formatPercent(summary.winRate)} icon={Target} note={summary.tradeCount ? `${summary.winningTrades} de ${summary.tradeCount} trades` : 'Sem trades no período.'} /><MetricTile label="Profit factor" value={summary.profitFactor == null ? 'Sem perdas na amostra' : summary.profitFactor.toFixed(2).replace('.', ',')} icon={Activity} note="Lucro bruto dividido pela perda bruta." /><MetricTile label="Drawdown máximo da amostra" value={summary.maxDrawdown == null ? '—' : formatCurrency(summary.maxDrawdown)} icon={TrendingDown} note="Maior queda do pico ao vale na sequência de trades." /></section>
    <section className="grid gap-4 xl:grid-cols-[1.4fr_1fr]"><Panel className="p-5 sm:p-6"><SectionHeading title="P&L acumulado" description={`${summary.tradeCount} trades · amostra sintética · não representa uma conta real.`} />{curve.length ? <div className="h-[300px]" role="img" aria-label="Curva de P&L acumulado"><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{ width: 600, height: 300 }}><AreaChart data={curve}><defs><linearGradient id="performance-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#b9f227" stopOpacity={0.2} /><stop offset="100%" stopColor="#b9f227" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.07)" vertical={false} /><XAxis dataKey="label" tick={{ fill: '#71717a', fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#71717a', fontSize: 10 }} axisLine={false} tickLine={false} tickFormatter={(value: number) => formatCurrency(value)} width={78} /><Tooltip formatter={(value) => [formatCurrency(Number(value)), 'P&L acumulado']} contentStyle={{ background: '#101214', border: '1px solid rgba(255,255,255,.12)', borderRadius: 10, color: '#f4f4f5', fontSize: 12 }} /><Area dataKey="cumulative" type="monotone" stroke="#b9f227" strokeWidth={2.5} fill="url(#performance-area)" /></AreaChart></ResponsiveContainer></div> : <EmptyState title="Sem resultados neste período" description="Amplie o intervalo ou remova filtros para incluir trades demonstrativos." />}</Panel>
      <Panel className="p-5 sm:p-6"><SectionHeading title="Composição da amostra" description="Valores originados dos mesmos registros filtrados." /><div className="grid grid-cols-2 gap-3"><div className="stat-tile"><p className="metric-label">Trades positivos</p><p className="mt-2 text-xl font-semibold text-[#b9f227]">{summary.winningTrades}</p></div><div className="stat-tile"><p className="metric-label">Trades negativos</p><p className="mt-2 text-xl font-semibold text-rose-300">{summary.losingTrades}</p></div><div className="stat-tile"><p className="metric-label">Resultado médio</p><p className="mt-2 text-sm font-semibold text-white">{formatCurrency(summary.averageTrade)}</p></div><div className="stat-tile"><p className="metric-label">Amostra</p><p className="mt-2 text-sm font-semibold text-white">{summary.tradeCount} trades</p></div></div><div className="mt-5 rounded-lg border border-white/[0.06] bg-white/[0.02] p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-zinc-500">Como ler</p><p className="mt-2 text-[11px] leading-5 text-zinc-400">O profit factor fica indefinido quando não há perdas na amostra. O drawdown é calculado pela ordem cronológica dos trades e não substitui os limites de uma corretora.</p></div></Panel></section>
    <Panel className="mt-5 overflow-hidden"><div className="p-5 sm:p-6"><SectionHeading title="Trades incluídos" description="Detalhes que compõem os indicadores acima." /></div>{trades.length ? <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-y border-white/[0.06] text-[9px] uppercase tracking-[0.14em] text-zinc-600"><th className="px-5 py-3">Data</th><th className="px-3 py-3">Conta</th><th className="px-3 py-3">Estratégia</th><th className="px-3 py-3">Instrumento</th><th className="px-5 py-3 text-right">P&amp;L líquido</th></tr></thead><tbody>{trades.map((trade) => <tr key={trade.id} className="border-b border-white/[0.04] last:border-0"><td className="px-5 py-3 text-[10px] text-zinc-500">{formatDateTime(trade.closedAt)}</td><td className="px-3 py-3 text-xs text-zinc-300">{workspace.accounts.find((account) => account.id === trade.accountId)?.name ?? 'Conta arquivada'}</td><td className="px-3 py-3 text-xs text-zinc-400">{workspace.strategies.find((strategy) => strategy.id === trade.strategyId)?.name ?? 'Sem estratégia'}</td><td className="px-3 py-3 font-mono text-[10px] text-zinc-500">{trade.instrument}</td><td className={`px-5 py-3 text-right font-mono text-xs ${trade.netPnl < 0 ? 'text-rose-300' : 'text-[#b9f227]'}`}>{formatCurrency(trade.netPnl)}</td></tr>)}</tbody></table></div> : <div className="px-5 pb-5"><EmptyState title="Nenhum trade para detalhar" description="Os filtros selecionados não correspondem a registros da amostra." /></div>}</Panel>
  </PageFrame>
}
